countries=c("Afeganistão"="AF","África do Sul"="ZA","Albânia"="AL","Alemanha"="DE","Andorra"="AD",
            "Angola"="AO","Anguilla"="AI","Antígua e Barbuda"="AG","Arábia Saudita"="SA",
            "Argélia"="DZ","Argentina"="AR","Armênia"="AM","Aruba"="AW","Austrália"="AU",
            "Áustria"="AT","Azerbaijão"="AZ","Bahamas"="BS","Bahrein"="BH","Bangladesh"="BD",
            "Barbados"="BB","Bélgica"="BE","Belize"="BZ","Benin"="BJ","Bermuda"="BM","Bielorrússia"="BY",
            "Bolívia"="BO","Bonaire"="XA","Bósnia e Herzegovina"="BA","Botsuana"="BW","Brasil"="BR",
            "Brunei"="BN","Bulgária"="BG","Burkina Faso"="BF","Burundi"="BI","Butão"="BT","Cabo Verde"="CV",
            "Camarões"="CM","Cambodia"="KH","Canadá"="CA","Catar"="QA","Cazaquistão"="KZ","Chade"="TD",
            "Chile"="CL","China"="CN","Chipre"="CY","Colômbia"="CO","Comores"="KM","Congo"="CG",
            "Coréia do Norte"="KP","Coreia do Sul"="KR","Costa Rica"="CR","Cote dIvoire"="CI",
            "Croácia"="HR","Cuba"="CU","Curaçao"="CW","Dinamarca"="DK","Djibouti"="DJ","Dominica"="DM",
            "Egito"="EG","El Salvador"="SV","Emirados Árabe Unidos"="AE","Equador"="EC","Eritreia"="ER",
            "Eslováquia"="SK","Eslovênia"="SI","Espanha"="ES","Estados Federados da Micronésia"="FM",
            "Estados Unidos da América"="US","Estônia"="EE","Etiópia"="ET","Fiji"="FJ","Filipinas"="PH",
            "Finlândia"="FI","França"="FR","Gabão"="GA","Gâmbia"="GM","Gana"="GH","Geórgia"="GE",
            "Gibraltar"="GI","Granada"="GD","Grécia"="GR","Groenlândia"="GL","Guadalupe"="GP",
            "Guam"="GU","Guatemala"="GT","Guernsey"="GG","Guiana"="GY","Guiana Francesa"="GF",
            "Guiné"="GN","Guiné Equatorial"="GQ","Guiné-Bissau"="GW","Haiti"="HT","Honduras"="HN",
            "Hungria"="HU","Iêmen"="YE","Ilha da Reunião"="RE","Ilha de Man"="IM","Ilha de São Martinho"="MF",
            "Ilhas Cayman"="KY","Ilhas Cook"="CK","Ilhas Faroé"="FO","Ilhas Malvinas"="FK",
            "Ilhas Marianas do Norte"="MP","Ilhas Marshall"="MH","Ilhas Maurício"="MU",
            "Ilhas Pitcairn"="PN","Ilhas Salomão"="SB","Ilhas Turcas e Caicos"="TC","Ilhas Vírgens Americanas"="VI",
            "Ilhas Vírgens Britânicas"="VG","Índia"="IN","Indonésia"="ID","Irã"="IR","Iraque"="IQ",
            "Irlanda"="IE","Islândia"="IS","Israel"="IL","Itália"="IT","Jamaica"="JM","Japão"="JP",
            "Jersey"="JE","Jerusalém"="PS","Jordânia"="JO","Kosovo"="XK","Kuwait"="KW","Laos"="LA",
            "Lesoto"="LS","Letônia"="LV","Líbano"="LB","Libéria"="LR","Líbia"="LY","Liechtenstein"="LI",
            "Lituânia"="LT","Luxemburgo"="LU","Macedônia do Norte"="MK","Madagascar"="MG","Malásia"="MY",
            "Malawi"="MW","Maldivas"="MV","Mali"="ML","Malta"="MT","Marrocos"="MA","Martinica"="MQ",
            "Mauritânia"="MR","Mayotte"="YT","México"="MX","Moçambique"="MZ","Moldávia"="MD","Mônaco"="MC",
            "Mongólia"="MN","Montenegro"="ME","Montserrat"="MS","Myanmar"="MM","Namíbia"="NA","Nauru"="NR",
            "Nepal"="NP","Nicarágua"="NI","Níger"="NE","Nigéria"="NG","Niue"="NU","Noruega"="NO",
            "Nova Caledônia"="NC","Nova Zelândia"="NZ","Omã"="OM","Países Baixos"="NL","Palau"="PW",
            "Panamá"="PA","Papua-Nova Guiné"="PG","Paquistão"="PK","Paraguai"="PY","Peru"="PE",
            "Polinésia Francesa"="PF","Polônia"="PL","Porto Rico"="PR","Portugal"="PT","Quênia"="KE",
            "Quirguistão"="KG","Quiribati"="KI","Reino Unido"="GB","República Centro-Africana"="CF",
            "República Democrática do Congo"="CD","República Dominicana"="DO","República Tcheca"="CZ",
            "Romênia"="RO","Ruanda"="RW","Rússia"="RU","Saba"="XC","Saint-Pierre e Miquelon"="PM",
            "Samoa"="WS","Samoa Americana"="AS","San Marino"="SM","Santa Helena"="SH","Santa Lúcia"="LC",
            "Santa Sé"="VA","Santo Eustáquio"="XB","São Bartolomeu"="BL","São Cristóvão e Névis"="KN",
            "São Tomé e Príncipe"="ST","São Vicente e Granadinas"="VC","Senegal"="SN","Serra Leoa"="SL",
            "Sérvia"="RS","Seychelles"="SC","Singapura"="SG","Sint Maarten"="SX","Síria"="SY","Somália"="SO",
            "Sri Lanka"="LK","Suazilândia"="SZ","Sudão"="SD","Sudão do Sul"="SS","Suécia"="SE","Suiça"="CH",
            "Suriname"="SR","Tailândia"="TH","Tajiquistão"="TJ","Tanzânia"="TZ","Timor-Leste"="TL",
            "Togo"="TG","Tokelau"="TK","Tonga"="TO","Trindade e Tobago"="TT","Tunísia"="TN",
            "Turcomenistão"="TM","Turquia"="TR","Tuvalu"="TV","Ucrânia"="UA","Uganda"="UG","Uruguai"="UY",
            "Uzbequistão"="UZ","Vanuatu"="VU","Venezuela"="VE","Vietnã"="VN","Wallis e Futuna"="WF",
            "Zâmbia"="ZM","Zimbábue"="ZW")